// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcmvSgRIwvJxKiaH4aiD9IJ5jC7r--n8',
    appId: '1:174517219106:web:67d5aa54447579c6593f7b',
    messagingSenderId: '174517219106',
    projectId: 'bukoo-e3efd',
    authDomain: 'bukoo-e3efd.firebaseapp.com',
    storageBucket: 'bukoo-e3efd.firebasestorage.app',
    measurementId: 'G-4KMB8JFWCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA92aSmYzn2MLFSYK6HhveYitVGKZIhgI',
    appId: '1:174517219106:android:2c651da8ed48a8a0593f7b',
    messagingSenderId: '174517219106',
    projectId: 'bukoo-e3efd',
    storageBucket: 'bukoo-e3efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfamnxuYGcgzd-q8x_kGTK0Fzfp09afhk',
    appId: '1:174517219106:ios:eef05e7ad893efb8593f7b',
    messagingSenderId: '174517219106',
    projectId: 'bukoo-e3efd',
    storageBucket: 'bukoo-e3efd.firebasestorage.app',
    iosBundleId: 'com.example.bukoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfamnxuYGcgzd-q8x_kGTK0Fzfp09afhk',
    appId: '1:174517219106:ios:eef05e7ad893efb8593f7b',
    messagingSenderId: '174517219106',
    projectId: 'bukoo-e3efd',
    storageBucket: 'bukoo-e3efd.firebasestorage.app',
    iosBundleId: 'com.example.bukoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTcmvSgRIwvJxKiaH4aiD9IJ5jC7r--n8',
    appId: '1:174517219106:web:2ee24e2ce0ecd368593f7b',
    messagingSenderId: '174517219106',
    projectId: 'bukoo-e3efd',
    authDomain: 'bukoo-e3efd.firebaseapp.com',
    storageBucket: 'bukoo-e3efd.firebasestorage.app',
    measurementId: 'G-FSKJGWFC7K',
  );
}
